name: Testing

on:
  push:
    branches:
      - main

jobs:
  send_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send HTTP request
        run: |
          curl -X GET https://a979-122-176-106-61.ngrok-free.app
